### ISSUE TITLE
Missing file (enrichTest_null.txt)

### ISSUE THREAD

**Issue by pmb59** [TheJacksonLaboratory/mia-sig#1]
In the [RNAPII ChIA-Drop data](https://github.com/TheJacksonLaboratory/mia-sig/wiki/Test-on-RNAPII-ChIA-Drop-data) tutorial, the file `GSM3347525NR_chr2L_FDR_0.1_pseudoGEM_1000_enrichTest_null.txt ` is asked by the function `plot_enrich_test_results.py ` but it doesn't seem to be generated after running the enrichment tests. Where can one generate this file?

Best wishes,
Pedro Madrigal

**Comment by minji011** [comment]
Hi Pedro,

I added a function to print out the null values file (GSM3347525NR_chr2L_FDR_0.1_pseudoGEM_1000_enrichTest_null.txt) in "freq_enrich_sigtest.py". 
Could you try to download the latest script and re-run the enrichment test? 

$ for chrom in $(cut -f1 ${data_dir}dm3.chrom.sizes); do qsub -F "--conf miasig_conf.sh --lib GSM3347525NRT --gen dm3 --fdr 0.1 --chr ${chrom} --sz 1000 --bs 10 --dir ${data_dir} --file GSM3347525NRT.txt" ${miasig_dir}freq_enrich_sigtest.pbs; done

Alternatively, you can download it here: https://thejacksonlaboratory.ent.box.com/s/hmj9p227q22g91iemw3k7o1i655xeghn/folder/79850917568

Minji

**Comment by pmb59** [comment]
thanks @minji011
